Add fill sensing messages
waterloo-rocketry/canlib pull request #26
Opened 2020-10-25 23:37 UTC by wendi-yu

Adds message format for fill sensing, as well as the message building and unpacking functions. Also did some drive by formatting cleanups.

2020-10-25 23:40 UTC, wendi-yu reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canlib/26)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jacobdeery and @zx100x100)

___
*[message_types.h, line 41 at r1](https://reviewable.io/reviews/waterloo-rocketry/canlib/26#-MKX7WIp5Bo0YrvNBz-K:-MKX7WIr5b2MlT7Bcqj7:b-v9fzhq) ([raw file](https://github.com/waterloo-rocketry/canlib/blob/ec3370b58f55d9a017908c459bea8d79da8cf0b0/message_types.h#L41)):*
> ```objc
> #define MSG_GPS_INFO              0x740
> 
> #define MSG_FILL_LVL              0x8E0
> ```

I kind of chose these at random from what hadn't been taken, not sure if they're actual good values?


<!-- Sent from Reviewable.io -->

2020-10-25 23:56 UTC, akmorrison requested changes

2020-10-25 23:56 UTC, akmorrison commented on message_types.h
> +#define MSG_FILL_LVL              0x8E0
2 things, 1) 0x7FF is the max SID, so you need the message type to be less than 0x7E0. 2) Please keep these in order, with lower number SID's defined earlier in the file (I see we broke this rule with MSG_LEDS_OFF, but in general)

2020-10-25 23:56 UTC, akmorrison commented on message_types.h
> + * FILL_LVL:        TSTAMP_MS_H TSTAMP_MS_M  TSTAMP_MS_L    FILL_LEVEL              DIRECTION       None            None            None
If you're gonna add a field like `DIRECTION`, you should probably define an enum so the values for `FILLING` and `EMPTYING` are clearly defined (since right now it's just an undocumented uint8_t). See `SENSOR_ID` or `BOARD_STATUS` enums below

2020-10-25 23:56 UTC, akmorrison commented on message_types.h
> + * (Version 0.0.4)
This number should probably match `CANLIB_VERSION` defined in `can.h` (currently 0.1.0), which got a minor number bump after IREC 2019 (b975d119a9)

2020-10-25 23:56 UTC, akmorrison commented on can_common.h
> +bool get_fill_info(const can_msg_t *msg,
should probably call this get_fill_lvl or something

2020-10-25 23:56 UTC, akmorrison commented on can_common.c
> +    if (!msg) { return false; }
If you're gonna check for null pointers on one of the arguments, you'd might as well check for the other two as well.

2020-10-26 18:24 UTC, wendi-yu commented on can_common.c
> +    if (!msg) { return false; }
I think `msg` is the only one that needs to not be null, since we're only reading from `msg` and not the other two?

2020-10-26 18:30 UTC, jacobdeery commented on can_common.c
> +    if (!msg) { return false; }
We're assigning to the other two, so if they're null it will still segfault

2020-11-03 01:17 UTC, dwkletke reviewed
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canlib/26)* status: all files reviewed, 7 unresolved discussions (waiting on @AidanHa, @akmorrison, @JaredWatson, @JoannaDiao, @wendi-yu, and @zx100x100)

___
*[message_types.h, line 92 at r3](https://reviewable.io/reviews/waterloo-rocketry/canlib/26#-MLAek6WB4_paVcsx0AW:-MLAek6WB4_paVcsx0AX:bt5q9ve) ([raw file](https://github.com/waterloo-rocketry/canlib/blob/5d72135884e0f7185173411ccbe9a4a2b6e44a57/message_types.h#L92)):*
> ```
> ·
> ```
Remove whitespace!


<!-- Sent from Reviewable.io -->

2020-11-18 04:04 UTC, zx100x100 requested changes
code looks good, but I'm disappointed in you Wendi, skipping out on the unit tests :sad-yeehaw:
In actuality canlib is one of the few embedded software projects with some unit testing, please add appropriate sections to the message build test

2020-12-17 03:34 UTC, zx100x100 commented on message_types.h
> +#define BOARD_ID_FILL_SPARE       0x10
decided that you should get it cause you where first, so ignore this

2020-12-17 03:38 UTC, zx100x100 approved these changes
All looks good
Should be good to merge

2020-12-24 04:12 UTC, zx100x100 commented
I'm learning about all this fun version stuff, I guess this should also include a minor rev increase.

2020-12-24 04:34 UTC, zx100x100 approved these changes
looks fantastic to me :fantasticstuff:

2020-12-24 15:15 UTC, akmorrison approved these changes

2020-12-24 21:59 UTC, merged