Increase gps coordinate precision
waterloo-rocketry/canlib pull request #28
Opened 2020-11-18 04:18 UTC by Rio6

This gives decimals an extra byte for gps latitude and longitude.

2020-11-22 04:39 UTC, zx100x100 requested changes
Please update the build message unit test, as well as reflect the changes to message format in message types.h
actual code looks good though!

2020-11-22 22:07 UTC, Rio6 commented
Updated unit test and found that I missed an F in the bit mask XD

They're fixed now

2020-11-27 04:28 UTC, zx100x100 approved these changes
Everything looks good, Nice work! :partyparrot:

2020-11-29 22:50 UTC, wendi-yu submitted a review, later dismissed
Yeah LGTM too, maybe also make the changes to parsley (in `cansw_usb`)?

2020-12-19 22:28 UTC, dwkletke approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canlib/28#-:-MOx6fIR-x9E0LUKRGlh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jacobdeery and @JaredWatson)



<!-- Sent from Reviewable.io -->

2020-12-24 01:46 UTC, jacobdeery requested changes
This is a canlib API change and should be accompanied by a version number update (line 12 in `can.h`)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canlib/28#-:-MPHQ3So-9wdClTMLbUu:b-p1k4n7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jacobdeery and @JaredWatson)



<!-- Sent from Reviewable.io -->

2020-12-25 19:45 UTC, Rio6 commented
> This is a canlib API change and should be accompanied by a version number update (line 12 in `can.h`)

Rebased to master and bumped to v0.3.0

2020-12-25 20:53 UTC, zx100x100 approved these changes
Looks good! :fantasticstuff:

2020-12-25 20:57 UTC, jacobdeery approved these changes
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canlib/28)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @dwkletke, @jacobdeery, and @JaredWatson)



<!-- Sent from Reviewable.io -->

2021-01-11 00:51 UTC, merged