fixed mama code to work on raw data
waterloo-rocketry/canlib pull request #33
Opened 2021-06-29 23:54 UTC by manumanuk

2021-06-30 02:11 UTC, zx100x100 requested changes
Looks like the get_radi_info function on line 630 hasn't been updated, that needs to happen

also just to confirm the switch here is from a floating point value representation to the raw ADC value? 

It would be much nicer if you can simply accept a single 16 bit integer instead of two 8 bit ones representing the high and low portions of the value. Inside the function you would then break the single value out into the two bytes needed for the CAN message.

Finally not sure if you did, but make sure you actually run the unit tests and make sure they pass

2021-07-04 03:49 UTC, manumanuk commented
* Changed get_radi_info function
* The floating point was the raw ADC value, yes
* Changed build_radi_info function to accept 16 bit value (do you want me to change get_radi_info to output a 16 bit too?
* Unit tests pass

2021-07-14 05:39 UTC, wendi-yu reviewed
code-wise this looks fine to me, I'll let Zach rereview on the board specifics though

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canlib/33#-:-MeYWh2D-I9La4s8AiRz:b-c7duoc)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @zx100x100)



<!-- Sent from Reviewable.io -->

2021-07-21 03:22 UTC, zx100x100 approved these changes
Aside from the one comment on adding a mask looks good to me. if you can address that it would be appreciated, but I'm not going to set the review as request changes

2021-07-21 03:22 UTC, zx100x100 commented on can_common.c
> +    output->data[5] = (uint8_t) (adc_value); // Lower byte
Adding a mask vs relying on the implicit truncation of casting it to a uint8_t would be nice

2021-07-29 00:51 UTC, BluCodeGH approved these changes
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canlib/33)* status: all files reviewed, 1 unresolved discussion (waiting on @manumanuk)



<!-- Sent from Reviewable.io -->

2021-07-29 00:51 UTC, merged