Remote arming
waterloo-rocketry/canlib pull request #34
Opened 2021-07-01 15:58 UTC by zx100x100

Adds support for remote arming

2021-07-01 16:13 UTC, Rio6 commented on can_common.c
> +    *altitude += ((uint32_t)msg->data[4] << 16);
Would `|=` be more suited here?

2021-07-02 18:51 UTC, BluCodeGH submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 4 files at r1, 1 of 4 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canlib/34#-:-MdcYoQ7CTX7cSCt68yS:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @jacobdeery, @JaredWatson, @MattiGen, @QuantumManiac, @wendi-yu, and @zx100x100)



<!-- Sent from Reviewable.io -->

2021-07-08 16:32 UTC, jacobdeery requested changes
Please add unit tests for the new functions

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canlib/34#-:-Me5xX6k2STOvSqZ7Fgx:b-7otf1y)* status: all files reviewed, 1 unresolved discussion (waiting on @JaredWatson, @MattiGen, @QuantumManiac, @wendi-yu, and @zx100x100)



<!-- Sent from Reviewable.io -->

2021-07-09 18:01 UTC, zx100x100 commented on can_common.c
> +    *altitude += ((uint32_t)msg->data[4] << 16);
does it make any difference?

2021-07-09 21:52 UTC, Rio6 commented on can_common.c
> +    *altitude += ((uint32_t)msg->data[4] << 16);
just looks better with bitwise stuff :P

2021-07-10 02:23 UTC, jacobdeery commented on can_common.c
> +    *altitude += ((uint32_t)msg->data[4] << 16);
Personally I find `|=` better for cases like this just because it makes it clear right away that `altitude` is meant to be a bitfield and not interpreted as an integer in its entirety. With `+=` I need to take a second to check if there's actually something different happening (note that the two are [_not_ equivalent in the general case](https://godbolt.org/z/qc9c9YeWs)).

2021-07-11 03:07 UTC, BluCodeGH reviewed
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canlib/34)* status: all files reviewed, 2 unresolved discussions (waiting on @JaredWatson, @MattiGen, @QuantumManiac, @Rio6, @wendi-yu, and @zx100x100)

___
*[message_types.h, line 76 at r5](https://reviewable.io/reviews/waterloo-rocketry/canlib/34#-MeIV0tJATJfEtxwX86V:-MeIV0tK4cEG0Y_Xic8-:b50lcs4) ([raw file](https://github.com/waterloo-rocketry/canlib/blob/93d855891d7e7bcbf8e967ee5f4d5a0df6a94843/message_types.h#L76)):*
> ```objc
> /*
>  * General message type format (from spread
>  sheet):
> ```

Unintentional keypress?


<!-- Sent from Reviewable.io -->

2021-07-11 13:54 UTC, zx100x100 reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canlib/34)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @BluCodeGH, @JaredWatson, @MattiGen, @QuantumManiac, @Rio6, and @wendi-yu)

___
*[message_types.h, line 76 at r5](https://reviewable.io/reviews/waterloo-rocketry/canlib/34#-MeIV0tJATJfEtxwX86V:-MeKqD7VEtUo9KxXzr2Y:b-5ndo44) ([raw file](https://github.com/waterloo-rocketry/canlib/blob/93d855891d7e7bcbf8e967ee5f4d5a0df6a94843/message_types.h#L76)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Unintentional keypress?
</blockquote></details>

guess so, fixed now


<!-- Sent from Reviewable.io -->

2021-07-12 23:30 UTC, jacobdeery approved these changes
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canlib/34)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @BluCodeGH, @JaredWatson, @MattiGen, @QuantumManiac, @Rio6, and @wendi-yu)



<!-- Sent from Reviewable.io -->

2021-07-12 23:32 UTC, BluCodeGH approved these changes
> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canlib/34)* status: all files reviewed, 1 unresolved discussion (waiting on @JaredWatson, @MattiGen, @QuantumManiac, @Rio6, and @wendi-yu)



<!-- Sent from Reviewable.io -->

2021-07-12 23:43 UTC, merged