Added picam boards and actuator type
waterloo-rocketry/canlib pull request #39
Opened 2022-03-24 01:55 UTC by cooperqb

Just added a few lines to message_types.h so account for the picams

2022-03-24 02:16 UTC, BluCodeGH requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canlib/39)* status: all files reviewed, 2 unresolved discussions (waiting on @cooperqb, @QuantumManiac, and @ZTeper)

___
*[message_types.h, line 75 at r1](https://reviewable.io/reviews/waterloo-rocketry/canlib/39#-MythDMb87G9503HXhhM:-MythDMb87G9503HXhhN:b-2s079v) ([raw file](https://github.com/waterloo-rocketry/canlib/blob/490895d3ffaee82909f4045f522a29b500a2df66/message_types.h#L75)):*
> ```objc
> #define BOARD_ID_ROCKET_PI_2       0X16
> #define BOARD_ID_ROCKET_PI_SPARE   0X17
> #define BOARD_ID_ROCKET_PI_SPARE_2 0X18
> ```

`ROCKET_PI_2_SPARE` to be consistent with the other boards (spare comes last)
___
*[message_types.h, line 115 at r1](https://reviewable.io/reviews/waterloo-rocketry/canlib/39#-MythJ5r0mQMsMFWIZP6:-MythJ5r0mQMsMFWIZP7:b-5w8ah6) ([raw file](https://github.com/waterloo-rocketry/canlib/blob/490895d3ffaee82909f4045f522a29b500a2df66/message_types.h#L115)):*
> ```objc
>  * PICAM_ON:        None        None         None           None                    None            None            None            None
>  * PICAM_OFF:       None        None         None           None                    None            None            None            None
>  * CAM_STAT:        TSTAMP_MS_H TSTAMP_MS_M  TSTAMP_MS_L    CAM_STATE               CMD_CAM_STATE   None            None            None
> ```

Out of date, remove.


<!-- Sent from Reviewable.io -->

2022-03-24 11:36 UTC, BluCodeGH approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canlib/39#-:-MyvhhAA2XDNKjZCWfDH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @QuantumManiac and @ZTeper)



<!-- Sent from Reviewable.io -->

2022-03-24 13:06 UTC, QuantumManiac approved these changes

2022-03-25 21:08 UTC, ZTeper approved these changes

2022-04-29 01:18 UTC, BluCodeGH commented
Please merge.

2022-04-30 21:22 UTC, merged