add radio curr type
waterloo-rocketry/canlib pull request #46
Opened 2023-03-13 04:30 UTC by yxyyeah

2023-03-13 22:22 UTC, Rio6 requested changes

2023-03-13 22:22 UTC, Rio6 commented on message_types.h
> +    SENSOR_RADIO_CURR,
This should be added to the very end so it doesn't mess with the existing enum numbers

2023-04-01 20:21 UTC, BluCodeGH submitted a review, later dismissed
@Rio6 pls re-review to not block

2023-04-01 20:27 UTC, Rio6 submitted a review, later dismissed

2023-05-29 22:08 UTC, BluCodeGH approved these changes

2023-05-29 22:11 UTC, merged