Refactor message build/get functions and add 2025 board IDs
waterloo-rocketry/canlib pull request #70
Opened 2024-11-06 20:09 UTC by JasonBrave

2024-11-13 03:46 UTC, celery6 requested changes

2024-11-13 03:46 UTC, celery6 commented on message_types.h
> +enum MESSAGE_TYPES {
![image](https://github.com/user-attachments/assets/e9f789b4-10a2-4e99-ad8e-fcdb37791700)

2024-11-13 03:46 UTC, celery6 commented on message_types.h
> +enum MESSAGE_PRIO {
naming convention same as below

2024-11-13 03:46 UTC, celery6 commented on message_types.h
> +enum BOARD_TYPE_ID {
naming convemtion

2024-11-13 03:46 UTC, celery6 commented on message/msg_common.h
> +#define SID(prio, msg)                                                                             \
does this need to be a macro

2024-11-13 15:15 UTC, JasonBrave commented on message/msg_common.h
> +#define SID(prio, msg)                                                                             \
This macro is just to replace previously copy and pasted logic OR

2024-11-17 05:59 UTC, celery6 approved these changes
lgtm

2024-11-18 19:05 UTC, merged